language: nix
sudo: required
env:
  global:
  - secure: hVm3IjX6uuERlYtpPfI/+7tEsi60CKTDrUhdgqNikfz4diNe1X7KT/SC0pk2w1PM2KK3Vj9D7ksDm3FcLbpvOHVFNEYV7e9x3oCaRUfxeD5jPZnzeQ2mrPkPsiUB/9TeNlSXnt9Hq5ghPNM88WPSHoOvEFG0OfWeGjtTdagz0x4EiBQODhaiP8UIQfQNTu71Xv/LfEoelmsoQydZw1+e6QTbL4bRNeb9YBLc1N1HkNk0Z4cRzpFcK3SU3MdIndXM6fMdz5pX+oKchkaCNh7bB2eUUw+9Jdrx08Fs3W+OXEwwiZGMG2y/rCPERRXMUK/XQVXwQWgzh+sjZCfyTaTOK8j0ahxQMUq5Op6sdrri4vuAEuvbIRZeUsqP3ZecnFT+a24l0HOs7YUHvlpfGf11CmVcwwfjbtb7XayQPew/IoU8oOiXPq1eUcMkPL3OpzW07zBSuilQm312eixOQLV2LjH8VazvanOH4D2SmyjdNiWNLMNobtc7FbKdbQO6krvJhEpF3WqwukQgg1KE/dTakjhQxqk8lCZkTEjbTwGEHkWczjlYta+crrf1rDVXHWOJBxkSP/oUbS2xiHxY004HI0DdbpBp4TsE3Gex73qnJaIJ7dkJNoFscmJnxKvnlv27mJwiTCJ1z9Oxv8KoAE9KBFCpg7kZMv6smo9Cki6jBNw=
before_script: sudo make travis-setup
script: make travis-run
